### ISSUE TITLE
Service catalog items on intorg type of site.

### ISSUE THREAD

**Issue by jpham2000** [SLAC-OCIO/slac-features#7]
I noticed that the services catalog items are no longer displayed under each category when a newly "internal org" site is provisioned.

For example: go to https://intorg-stage.slac.stanford.edu/services and click on "Application Support" category, you'll get a message that said "The services for this category have not yet been defined." . There is at least one catalog item under this category as far as I know.
![sc-items](https://cloud.githubusercontent.com/assets/3847783/5322374/e5e5b368-7c79-11e4-922d-35ddf6bf1dfb.png)

**Comment by xalgorithm** [comment]
fixed in #39
